### ISSUE TITLE
"Drop a single <script> tag into your html and you're done" isn't quite true

### ISSUE THREAD

**Issue by Pomax** [browserify/browserify-website#23]
The website finishes the browserify process with "Drop a single `<script>` tag into your html and you're done!" but this isn't quite true. Now the bundle's loaded, but if that bundle's purpose is to export an object for other on-page scripts to use, how do you use it? There's no `require` built into the browser, so how do I now use the browserify-built library without still needing a module loader like `require.js`? It'd be super helpful to see that last missing step added to the page.

(bundling with browserify generates code that cannot just be wrapped in `var mylib = ( ...... );`, so the main problem I have atm is how to use the generated code in an otherwise vanilla JS page)

**Comment by goto-bus-stop** [comment]
the --standalone flag does this and is mentioned in the [browserify handbook](https://github.com/browserify/browserify-handbook#standalone); i don't think we need to mention it in the "your first bundle" section because the assumption is that you're actually running the script itself.
