### ISSUE TITLE
Doesn't add semicolon to end of file

### ISSUE THREAD

**Issue by keven425** [browserify/browserify-website#26]
This will throw error when concatenating browserified file with other angular modules.

e.g.

Uncaught Error: Cannot find module 'function (z,f,T){'use strict';f.module("ngAnimate",["ng"]).factory("$$animateReflow",["$window","$timeout","$document",function(f,h,d){var n=f.requestAnimationFrame||f.webkitRequestAnimationFrame||function(d){ret...<omitted>...}'

**Comment by goto-bus-stop** [comment]
dupe of https://github.com/browserify/browserify/issues/1351
