### ISSUE TITLE
Add a license for the site

### ISSUE THREAD

**Issue by caleb** [browserify/browserify-website#29]
Hi,

I created a browserify plugin for broccolijs and want to make a derivative logo with the broccoli wearing the browserify wizard hat but I can't find a license for the wizard hat logo.

I know the site is open source, but I didn't want to use anything I wasn't supposed to.

Thanks!

**Comment by dcousens** [comment]
@substack can you address this?

`crypto-browserify` (as used by `browserify`) is using a derivative logo,  and I'd prefer if it was licensed appropriately...

![](https://avatars2.githubusercontent.com/u/6728527?s=200&v=4)

**Comment by substack** [comment]
The browserify logo image is stored in the browserify repo under `assets/logo.png` so the copyright license terms of the browserify project should apply. There are no other special protections such as trademark.

**Comment by substack** [comment]
I designed the logo so consider it released under the same as the browserify project itself.

**Comment by dcousens** [comment]
Thanks @substack ,  closing this as I don't think it reasonable to bother to LICENSE any remaining aspects of the site at this time as it would be tedious without gain.
