### ISSUE TITLE
pass 3rd party static checkers

### ISSUE THREAD

**Issue by raould** [browserify/browserify-website#43]
hi, It would be super hyper awesome great if Browserify could generate JS that passed Facebook Flow and also ESLint (in e.g. "standard" mode). At the moment it generates a lot of complaints from either one it seems to me? Thanks.

**Comment by goto-bus-stop** [comment]
You should run Flow or ESLint on your source files and ignore the bundle using an `.eslintignore` file or the equivalent for Flow. If dependencies don't pass ESlint or Flow, browserify cannot do anything to fix that.
