### ISSUE TITLE
browserify chokes on require ('openpgp')

### ISSUE THREAD

**Issue by tgregoneil** [browserify/browserify-website#44]
Test file contains one line:
<code>var openpgp = require ('openpgp');</code>

browserfying this file reports:

```
Error: Cannot find module './config' from '/usr/lib/node_modules/openpgp/dist'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

openpgp's package.json file contains the key:  "directories":{"lib":"src"}.  Shouldn't this be enough for browserify to find the needed require references in the src hierarchy?

This is on the latest versions as of last night:  openpgp@2.2.2  browserify@13.0.0

**Comment by smcatala** [comment]
works fine with the following entry in your module's `package.json`:
```
  "browser": {
    "openpgp": "openpgp/dist/openpgp.min.js"
  }
```

**Comment by goto-bus-stop** [comment]
Fixed in https://github.com/openpgpjs/openpgpjs/pull/491

**Comment by tgregoneil** [comment]
Sweet. Just tested with openpgp v 2.6.2. Browserify now handles require ('openpgp') like a champ. Thanks!
