### ISSUE TITLE
Unable to install correctly 

### ISSUE THREAD

**Issue by Younesi** [browserify/browserify-website#47]
Hi, I want to install [ng-if-bootstrap-grid](https://github.com/xErik/ng-if-bootstrap-grid)
Which needs **require** function so I decided to install Browserify
I run the install command: `npm install -g browserify`
my code is:
              `angular.module('myApp',require('ng-if-bootstrap-grid').name);`
but I get the error : 
**Uncaught ReferenceError: require is not defined** 
Am I making a mistake here or it's .... ?

**Comment by goto-bus-stop** [comment]
You have to run browserify on your application code and then use the resulting bundle file in a `<script>` tag. Closing because it has been a long time, please reopen if this is still an issue.
