### ISSUE TITLE
No demo works for me on http://browserify.org/demos.html

### ISSUE THREAD

**Issue by konrados** [browserify/browserify-website#48]
Hi,

On this website: http://browserify.org/demos.html no demo seems to work. Chrome 52.0.2743.116 (64-bit), nothing in console.

**Comment by SaurabhBayani** [comment]
@konrados  Can you please check again? Seems to be working fine on all browsers. May be related to some cache thing

**Comment by goto-bus-stop** [comment]
Please reopen if this is still an issue.
