### ISSUE TITLE
requirebin iframe not working in demos page

### ISSUE THREAD

**Issue by CodeDoes** [browserify/browserify-website#64]
http://browserify.org/demos.html
the second iframe doesn't work

**Comment by anvaka** [comment]
Seems like all demos are broken

**Comment by JGCreator** [comment]
Demos are broken
![image](https://user-images.githubusercontent.com/5280734/128387675-217c72b9-911e-4619-a0ce-3e749a56c667.png)

**Comment by gharman** [comment]
Looks like the place they were hosted lost its domain (presumably no longer in operation)

![image](https://user-images.githubusercontent.com/5117858/179866213-25fb7005-ef2f-4a47-952d-803261a1692b.png)

**Comment by goto-bus-stop** [comment]
addressed in 8a2ee055596d7877a34feb2d4bbadd4717cf9f1d. thanks!
